In [2]:
import numpy as np
import os

In [4]:
dpath = "mnist_subset"
train_data_path = os.path.join(dpath, "train_images.npy")
train_label_path = os.path.join(dpath, "train_labels.npy")
X = np.load(train_data_path)
y = np.load(train_label_path)
print(X.shape, y.shape)


(2000, 784) (2000, 10)


In [5]:
print(X[0].shape)

(784,)


In [18]:
np.random.seed(8)
x = np.arange(3) + 1
W = np.random.randint(0,5,size=(1,3))
x = x[:,None]
print(x)
print(W)
print(x @ W)
print(x * W)
X = np.random.randint(0,5,size=(2,2))
print(X)

[[1]
 [2]
 [3]]
[[3 4 1]]
[[ 3  4  1]
 [ 6  8  2]
 [ 9 12  3]]
[[ 3  4  1]
 [ 6  8  2]
 [ 9 12  3]]
[[1 2]
 [0 3]]


In [7]:
np.random.seed(69)
x = np.arange(3) + 1
X = np.random.randint(0,5,size=(4,3))
w = np.random.randint(0,5,size=(5))
print(X)
print(x)
print(w)
#print(np.einsum('i,ij->i', x, w[:,None]))
t = np.einsum('ki,ij->kij',X,w[None,:])
print(t, t.shape)
print(np.einsum('ki,ij->ij',X,w[None,:]))

[[3 1 3]
 [2 4 1]
 [1 0 1]
 [0 0 4]]
[1 2 3]
[2 4 3 3 0]
[[[ 6 12  9  9  0]
  [ 2  4  3  3  0]
  [ 6 12  9  9  0]]

 [[ 4  8  6  6  0]
  [ 8 16 12 12  0]
  [ 2  4  3  3  0]]

 [[ 2  4  3  3  0]
  [ 0  0  0  0  0]
  [ 2  4  3  3  0]]

 [[ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 8 16 12 12  0]]] (4, 3, 5)
[[12 24 18 18  0]
 [10 20 15 15  0]
 [18 36 27 27  0]]


In [25]:
Y = np.random.randint(0,2, size=(5,6))
print(Y)
print(np.sum(Y,axis=1))
Z = Y / np.sum(Y,axis=1)[:,None]
print(Y+1)
print((Y+1) * (Y+1))

[[1 0 1 0 1 0]
 [0 1 1 0 1 1]
 [0 1 0 1 0 1]
 [1 0 1 0 0 1]
 [0 1 0 0 0 0]]
[3 4 3 3 1]
[[2 1 2 1 2 1]
 [1 2 2 1 2 2]
 [1 2 1 2 1 2]
 [2 1 2 1 1 2]
 [1 2 1 1 1 1]]
[[4 1 4 1 4 1]
 [1 4 4 1 4 4]
 [1 4 1 4 1 4]
 [4 1 4 1 1 4]
 [1 4 1 1 1 1]]
